# Generated by Django 3.2.9 on 2021-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
